
// THIS FILE IS AUTO-GENERATED BY `routes-manifest-generate.ts`!

import ___resources_index_html_ts from './resources/index.html.ts';
import ___resources_writing_html_ts from './resources/writing.html.ts';
import ___resources_art_html_ts from './resources/art.html.ts';
import ___resources_projects_html_ts from './resources/projects.html.ts';
import ___resources_feed_xml_ts from './resources/feed.xml.ts';
import ___resources_blog_index_html_ts from './resources/blog/index.html.ts';
import ___resources_blog__id__html_ts, { params as ___resources_blog__id__html_ts_params } from './resources/blog/[id].html.ts';
import ___resources_404_html_ts from './resources/404.html.ts';

type Route = { default: (param?: string) => (string | Promise<string>), params?: string[] }

const routes: {[key: string]: Route} = {
    ['./resources/index.html.ts']: { default: ___resources_index_html_ts },
    ['./resources/writing.html.ts']: { default: ___resources_writing_html_ts },
    ['./resources/art.html.ts']: { default: ___resources_art_html_ts },
    ['./resources/projects.html.ts']: { default: ___resources_projects_html_ts },
    ['./resources/feed.xml.ts']: { default: ___resources_feed_xml_ts },
    ['./resources/blog/index.html.ts']: { default: ___resources_blog_index_html_ts },
    ['./resources/blog/[id].html.ts']: { default: ___resources_blog__id__html_ts, params: ___resources_blog__id__html_ts_params },
    ['./resources/404.html.ts']: { default: ___resources_404_html_ts }
}

export default (module: string) => routes[module]
